# data
data_base_dir: /large/naru/EgoHand/data
data_dir: ${data_base_dir}/ee4d/ee4d_motion_uniegomotion/uniegomotion/ee_train_joints_tips.pt
data_dir_eval: ${data_base_dir}/ee4d/ee4d_motion_uniegomotion/uniegomotion/ee_val_joints_tips.pt
pattern: "*.npy"

# precomputed cache (set use_cache: true to load from precomputed pt)
use_cache: true
cache_pt: ./data/preprocessed_motion_train.pt
cache_pt_eval: ./data/preprocessed_motion_val.pt

# frequently changed
use_root_loss: false
base_idx: 15
hand_local: true
code_dim: 256
K: 1024
T: 21
body_tokens_per_t: 4


# eval
eval_every: 1
eval_num_save_samples: 5
eval_batch_size: 32
eval_vis_dir: ${save_dir}/eval
eval_save_vis_every: 100
eval_check: false

# system
seed: 0
device: cuda
num_workers: 18

# training
batch_size: 256
epochs: 3000
lr: 0.00001
wd: 0.000001
grad_clip: 1
log_every: 1
ckpt_every: 1000
joints_loss: false
joints_loss_weight: 5.0

# model


ema_decay: 0.99
alpha_commit: 2
hand_tokens_per_t: ${body_tokens_per_t}
body_down: 1
hand_down: 1
enc_depth: 6
enc_heads: 8
mlp_ratio: 4.0
alpha_root: 5.0
alpha_body: 1.0
alpha_hand: 1.0
enc_type_B: "cnn"
enc_type_H: "cnn"
enc_use_attn_B: False 
enc_use_attn_H: False
enc_use_pos: False
enc_post_mlp: False

decoder_mode: vq   # or flow
log_recon_every: 200  # flow時にサンプル生成してログする頻度（0で無効）
flow_sample_steps: 30
flow_solver: heun     # euler or heun

flow_sample_steps_eval: 15
flow_solver_eval: euler
# cnn
cnn_width_B: 256
cnn_depth_B: 8
cnn_width_H: 256
cnn_depth_H: 8
cnn_dilation_max: 8
cnn_drop: 0.0
dec_hid: 256

hand_in_dim: 480
body_in_dim: 263

# normalize
normalize: true
mean_path: ./preprocess/statistics/tips/mean.npy
std_path: ./preprocess/statistics/tips/std.npy


include_fingertips: true


name: ${decoder_mode}/hand_local_${hand_local}/base_${base_idx}/T_${T}/trans_${use_root_loss}/token_${body_tokens_per_t}/code_dim_${code_dim}/K_${K}/final
save_dir: ./runs/${name}
project: h2vq_vqvae